
LAYOUTS = {
    'US':  ur"""`1234567890-=qwertyuiop[]\asdfghjkl;'zxcvbnm,./~!@#$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:"ZXCVBNM<>?""",
    'DE':  ur"""^1234567890'#qwertzuiopöü*asdfghjkl;äyxcvbnm,.-°!"§$%&/()=?ßQWERTZUIOPÖÜ+ASDFGHJKL:ÄYXCVBNM<>_""",
    'SPi': ur"""|1234567890'¿qwertyuiop{}*asdfghjkl;ñzxcvbnm,.-°!"#$%&/()=?¡QWERTYUIOP[]+ASDFGHJKL:ÑZXCVBNM<>_""",
    'FR':  ur"""!&é"'(-è_çà)=azertyuiopmù°qsdfghjkl;*wxcvbn,,./§1234567890£$AZERTYUIOPM%+QSDFGHJKL:μWXCVBN?<>²""",
    'IT':  ur"""\1234567890*+qwertyuiopùòlasdfghjk<;'zxcvbnm,.-|!"£$%&/()=èéQWERTYUIOP§çLASDFGHJK>:?ZXCVBNM°à_""",
    'PTb': ur"""'1234567890-=qwertyuiop[]lasdfghjkÇ;´zxcvbnm,./"!@#$%¨&*()_+QWERTYUIOP{}LASDFGHJKç:`ZXCVBNM<>?""",  # Win.
    'PTp': ur"""\1234567890*+qwertyuiop«çlasdfghjk<;´zxcvbnm,.-|!"#$%&/()=?'QWERTYUIOP»ÇLASDFGHJK>:`ZXCVBNMºª_""",  # Win.
    'PTa': ur"""§1234567890*+qwertyuiop~çªasdfghjkl;´zxcvbnm,.-±!"#$%&/()=?'QWERTYUIOP^ÇºASDFGHJKL:`ZXCVBNM<>_""",  # Apple
    'SP':  ur"""º1234567890'¡qwertyuiopñç*asdfghjkl;´zxcvbnm,.-ª!"·$%&/()=?¿QWERTYUIOPÑÇ+ASDFGHJKL:¨ZXCVBNM<>_""",  # y SPI (Apple)
    'BRw': ur"""`1234567890~#qwertyuiop[]_asdfghjkl;'zxcvbnm,./¬!"£$%^&*()-=QWERTYUIOP{}+ASDFGHJKL:@ZXCVBNM<>?""",  # Win.
    'BRa': ur"""§1234567890-=qwertyuiop[]\asdfghjkl;'zxcvbnm,./±!@£$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:"ZXCVBNM<>?""",  # Apple
}

GLYPH_NAMES = {
    u'1': u'one',
    u'2': u'two',
    u'3': u'three',
    u'4': u'four',
    u'5': u'five',
    u'6': u'six',
    u'7': u'seven',
    u'8': u'eight',
    u'9': u'nine',
    u'0': u'zero',
    u'`': u'grave',
    u'-': u'hyphen',
    u'=': u'equal',
    u'[': u'bracketleft',
    u']': u'bracketright',
    u'\\': u'backslash',
    u';': u'semicolon',
    u'\'': u'quotesingle',
    u',': u'comma',
    u'.': u'period',
    u'/': u'slash',
    u'~': u'asciitilde',
    u'!': u'exclam',
    u'@': u'at',
    u'#': u'numbersign',
    u'$': u'dollar',
    u'%': u'percent',
    u'^': u'asciicircum',
    u'&': u'ampersand',
    u'*': u'asterisk',
    u'(': u'parenleft',
    u')': u'parenright',
    u'_': u'underscore',
    u'+': u'plus',
    u'{': u'braceleft',
    u'}': u'braceright',
    u'|': u'bar',
    u':': u'colon',
    u'\"': u'quotedbl',
    u'<': u'less',
    u'>': u'greater',
    u'?': u'question',
    u'ß': u'germandbls',
    u'´': u'acute',
    u'ü': u'udieresis',
    u'ö': u'odieresis',
    u'ä': u'adieresis',
    u'§': u'section',
    u'Ü': u'Udieresis',
    u'Ö': u'Odieresis',
    u'Ä': u'Adieresis',
    u'¡': u'exclamdown',
    u'¿': u'questiondown',
    u'ç': u'ccedilla',
    u'ñ': u'ntilde',
    u'·': u'periodcentered',
    u'Ç': u'Ccedilla',
    u'Ñ': u'Ntilde',
    u'¨': u'dieresis',
    u'é': u'eacute',
    u'à': u'agrave',
    u'ù': u'ugrave',
    u'°': u'degree',
    u'£': u'sterling',
    u'è': u'egrave',
    u'ì': u'igrave',
    u'ò': u'ograve',
    u'º': u'ordmasculine',
    u'ª': u'ordfeminine',
    u'¬': u'logicalnot',
    u'μ': u'mu',
    u'²': u'twosuperior',
    u'«': u'guillemotleft',
    u'»': u'guillemotright',
    u'±': u'plusminus'
}


def getGlyphNamesofLayout(layoutKey):
    return [GLYPH_NAMES[c].encode('utf-8') if c in GLYPH_NAMES else c.encode('utf-8') for c in LAYOUTS[layoutKey]]
